apiVersion: v1
kind: Service
metadata:
  name: backendapiservice
spec:
  selector:
    app: backendpods
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 30001
      nodePort: 30000
